In [11]:
# Importing relevant libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

le=LabelEncoder()
from sklearn.neural_network import MLPClassifier

# Importing data from the dataset
Emp = pd.read_excel(r'E:\Projects\DATASCIENCE & AI\Internship Projects\Employee-Performance-Analysis--INX-Future-Inc\data\processed\INX_Future_Inc_Employee_Performance_CDS_Project2_Data_V1.8.xlsx')

In [12]:
#Reading the first 3 rows
Emp.head(3)

EmpNumber  Age Gender EducationBackground MaritalStatus EmpDepartment  \
0  E1001000   32   Male           Marketing        Single         Sales   
1  E1001006   47   Male           Marketing        Single         Sales   
2  E1001007   40   Male       Life Sciences       Married         Sales   

        EmpJobRole BusinessTravelFrequency  DistanceFromHome  \
0  Sales Executive           Travel_Rarely                10   
1  Sales Executive           Travel_Rarely                14   
2  Sales Executive       Travel_Frequently                 5   

   EmpEducationLevel  ...  EmpRelationshipSatisfaction  \
0                  3  ...                            4   
1                  4  ...                            4   
2                  4  ...                            3   

   TotalWorkExperienceInYears  TrainingTimesLastYear  EmpWorkLifeBalance  \
0                          10                      2                   2   
1                          20                      2                   3   
2                          20                      2                   3   

   ExperienceYearsAtThisCompany  ExperienceYearsInCurrentRole  \
0                            10                             7   
1                             7                             7   
2                            18                            13   

  YearsSinceLastPromotion  YearsWithCurrManager  Attrition  PerformanceRating  
0                       0                     8         No                  3  
1                       1                     7         No                  3  
2                       1                    12         No                  4  

[3 rows x 28 columns]

In [13]:
# To convert all the features into INT with Label encoder
Emp.Gender=le.fit_transform(Emp.Gender)
Emp.EducationBackground=le.fit_transform(Emp.EducationBackground)
Emp.MaritalStatus=le.fit_transform(Emp.MaritalStatus)
Emp.BusinessTravelFrequency=le.fit_transform(Emp.BusinessTravelFrequency)
Emp.OverTime=le.fit_transform(Emp.OverTime)
Emp.EmpJobRole=le.fit_transform(Emp.EmpJobRole)
Emp.EmpDepartment=le.fit_transform(Emp.EmpDepartment)
Emp.Attrition=le.fit_transform(Emp.Attrition)

In [14]:
#Seting the target and predictor variables
X=Emp.loc[:,'Age':'Attrition']
y=Emp.loc[:,'PerformanceRating']

- We then split the dataset into two sets: training set and testing set. As the name implies, the training set will be used when training the model and the testing to test its predictive capability.

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=5)

In [16]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 900 entries, 811 to 867
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Age                           900 non-null    int64
 1   Gender                        900 non-null    int64
 2   EducationBackground           900 non-null    int64
 3   MaritalStatus                 900 non-null    int64
 4   EmpDepartment                 900 non-null    int64
 5   EmpJobRole                    900 non-null    int64
 6   BusinessTravelFrequency       900 non-null    int64
 7   DistanceFromHome              900 non-null    int64
 8   EmpEducationLevel             900 non-null    int64
 9   EmpEnvironmentSatisfaction    900 non-null    int64
 10  EmpHourlyRate                 900 non-null    int64
 11  EmpJobInvolvement             900 non-null    int64
 12  EmpJobLevel                   900 non-null    int64
 13  EmpJobSatisfaction            900 non-

- All the features in this dataset converted into INT datatype

In [17]:
# To check the Shape of X_train
X_train.shape

(900, 26)

In [18]:
# To check the Shape of X_test
X_test.shape

(300, 26)

In [19]:
# To check the Shape of y_train
y_train.shape

(900,)

In [20]:
# To check the Shape of y_test
y_test.shape

(300,)

 ### The Random Forest is chosen over other algorithms because it uses the entire dataset optimally which reduces bias error. The algorithm is also famous for providing maximum reduction in variance as it gives the average output from an ensemble of several decision trees,hence the name ‘Random Forest’.

- We then train the Random Forest Classifier model:

In [21]:
# Train the Random forest classifoer
from sklearn.ensemble import RandomForestClassifier
RFC= RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=500)
RFC.fit(X_train,y_train)

RandomForestClassifier(n_estimators=500, n_jobs=2, oob_score=True)

In [22]:
DC= DecisionTreeClassifier(random_state=0)
DC.fit(X_train,y_train)

DecisionTreeClassifier(random_state=0)

In [23]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, y_train)

SVC()

# Predicting Model 

In [24]:
#Applying Calssifier to Test data
y_predict=RFC.predict(X_test)
y_predict

array([3, 2, 3, 3, 3, 3, 3, 3, 2, 4, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 2, 3,
       3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 3, 2, 3, 3,
       3, 3, 2, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 2, 3, 3, 3, 3,
       3, 3, 2, 3, 3, 3, 3, 3, 4, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3,
       3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 4, 3, 2, 3, 3, 3,
       3, 4, 3, 3, 2, 4, 3, 3, 2, 2, 3, 4, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 4, 3, 4,
       3, 4, 3, 4, 2, 3, 3, 3, 3, 3, 4, 4, 3, 2, 3, 3, 3, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3,
       3, 3, 4, 2, 3, 4, 3, 3, 2, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       4, 3, 2, 3, 3, 2, 3, 3, 4, 3, 3, 4, 3, 2, 3, 3, 2, 3, 2, 3, 3, 3,
       3, 3, 3, 3, 3, 2, 3, 4, 3, 3, 3, 2, 3, 2, 3, 2, 3, 3, 2, 4, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 2, 3, 3, 3])

In [25]:
# Calculating Accuracy Score
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
acc=accuracy_score(y_test,y_predict)
acc

0.9333333333333333

- There are very few mis -classifications and the precision rates for all the values are very high as seen from the below output  and it implies that our model is highly accurate.

In [26]:
# Classification Report
cr=classification_report(y_test,y_predict)
print(cr)

              precision    recall  f1-score   support

           2       0.88      0.88      0.88        48
           3       0.95      0.97      0.96       224
           4       0.91      0.75      0.82        28

    accuracy                           0.93       300
   macro avg       0.91      0.86      0.89       300
weighted avg       0.93      0.93      0.93       300



In [27]:
cm=confusion_matrix(y_test,y_predict)
print(cm)

[[ 42   6   0]
 [  5 217   2]
 [  1   6  21]]


In [28]:
#Cross Validation

pd.crosstab(y_test,y_predict,rownames=['Actual'],colnames=['Prediction'],margins=True)

Prediction   2    3   4  All
Actual                      
2           42    6   0   48
3            5  217   2  224
4            1    6  21   28
All         48  229  23  300

# DecisionTree

In [29]:
#Applying Calssifier to Test data
y_predict1=model.predict(X_test)
y_predict1

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [30]:
# Calculating Accuracy Score
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
acc=accuracy_score(y_test,y_predict1)
acc

0.7466666666666667

In [31]:
# Classification Report
cr=classification_report(y_test,y_predict1)
print(cr)

              precision    recall  f1-score   support

           2       0.00      0.00      0.00        48
           3       0.75      1.00      0.85       224
           4       0.00      0.00      0.00        28

    accuracy                           0.75       300
   macro avg       0.25      0.33      0.28       300
weighted avg       0.56      0.75      0.64       300



E:\Projects\DATASCIENCE & AI\Internship Projects\Employee-Performance-Analysis--INX-Future-Inc\.EmP\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
E:\Projects\DATASCIENCE & AI\Internship Projects\Employee-Performance-Analysis--INX-Future-Inc\.EmP\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
E:\Projects\DATASCIENCE & AI\Internship Projects\Employee-Performance-Analysis--INX-Future-Inc\.EmP\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined an

In [32]:
cm=confusion_matrix(y_test,y_predict1)
print(cm)

[[  0  48   0]
 [  0 224   0]
 [  0  28   0]]


In [33]:
#Cross Validation

pd.crosstab(y_test,y_predict1,rownames=['Actual'],colnames=['Prediction'],margins=True)

Prediction    3  All
Actual              
2            48   48
3           224  224
4            28   28
All         300  300

# SVM

In [34]:
#Applying Calssifier to Test data
y_predict2=model.predict(X_test)
y_predict2

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [35]:
# Calculating Accuracy Score
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
acc=accuracy_score(y_test,y_predict2)
acc

0.7466666666666667

In [36]:
# Classification Report
cr=classification_report(y_test,y_predict2)
print(cr)

              precision    recall  f1-score   support

           2       0.00      0.00      0.00        48
           3       0.75      1.00      0.85       224
           4       0.00      0.00      0.00        28

    accuracy                           0.75       300
   macro avg       0.25      0.33      0.28       300
weighted avg       0.56      0.75      0.64       300



E:\Projects\DATASCIENCE & AI\Internship Projects\Employee-Performance-Analysis--INX-Future-Inc\.EmP\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
E:\Projects\DATASCIENCE & AI\Internship Projects\Employee-Performance-Analysis--INX-Future-Inc\.EmP\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
E:\Projects\DATASCIENCE & AI\Internship Projects\Employee-Performance-Analysis--INX-Future-Inc\.EmP\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined an

In [37]:
cm=confusion_matrix(y_test,y_predict2)
print(cm)

[[  0  48   0]
 [  0 224   0]
 [  0  28   0]]


In [38]:
#Cross Validation

pd.crosstab(y_test,y_predict2,rownames=['Actual'],colnames=['Prediction'],margins=True)

Prediction    3  All
Actual              
2            48   48
3           224  224
4            28   28
All         300  300

# Neural Network 

In [39]:
# Train MLP Classifier
mlp_clf = MLPClassifier(hidden_layer_sizes=(64, 32), activation='relu', max_iter=1000, random_state=42)
mlp_clf.fit(X_train, y_train)


MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1000, random_state=42)

In [40]:

# Predict on test set
y_pred = mlp_clf.predict(X_test)

In [41]:
# Evaluation
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [42]:




# Print results
print(f"Accuracy: {accuracy:.3f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

Accuracy: 0.803
Confusion Matrix:
[[ 27  20   1]
 [  9 200  15]
 [  2  12  14]]
Classification Report:
              precision    recall  f1-score   support

           2       0.71      0.56      0.63        48
           3       0.86      0.89      0.88       224
           4       0.47      0.50      0.48        28

    accuracy                           0.80       300
   macro avg       0.68      0.65      0.66       300
weighted avg       0.80      0.80      0.80       300

